version: "3"

services:
  spring-bd:
    container_name: spring_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: spring_db
      POSTGRES_USER: spring_db
      POSTGRES_DB: spring_db
    ports:
      - "5432:5432"